users/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views
app_name='users'
urlpatterns = [
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

web/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace='users')),
    path('',include('webapp.urls',namespace='webapp')),

]

webapp/urls.py
from django.urls import path
from . import views
app_name='webapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('topics',views.topics,name='topics'),
    path('topic/<int:topic_id>/',views.topic, name='topic'),
    path('new_topic',views.new_topic,name='new_topic'),
    path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),
]

users/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.text

class Entry (models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

webapp/forms.py
from django import forms
from  .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import logout,login,authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('webapp:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticate_user = authenticate(username=new_user.username,password = request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('webapp:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

webapp/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import  HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'webapp/index.html')

@login_required
def topics(request):

    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'webapp/topics.html', context)

@login_required
def topic(request, topic_id):

    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'webapp/topic.html', context)

@login_required
def new_topic(request):
    if request.method !='POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
        return HttpResponseRedirect(reverse('webapp:topics'))
    context = {'form': form}
    return render(request,'webapp/new_topic.html',context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('webapp:topic',args=[topic_id]))

    context = {'topic':topic, 'form':form}
    return render(request, 'webapp/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('webapp:topic',args=[topic.id]))

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'webapp/edit_entry.html',context)

users/templates/users/login.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>登陆你的账户吧</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">登陆</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'webapp:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}

{% block content %}
<form method="post" action="{% url 'users:register' %}" class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button name="submit">注册</button>
{% endbuttons %}
<input type="hidden" name="next" value="{% url 'webapp:index' %}" />
</form>
{% endblock content %}

webapp/templates/webapp/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>董岩的blog</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'webapp:index' %}">
                董岩的blog</a>
            </div>

            <div class="collapse navbar-collapse" id="navbarText">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webapp:topics' %}">主题<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                       <a class="nav-link">Hello, {{ user.username }}.</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">注销</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">注册</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">登陆</a></li>
                {% endif %}
            </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
    </body>
</html>

webapp/templates/webapp/edit_entry.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}
{% block hesder %}
    <h2>编辑你的条目</h2>
{% endblock hesder %}

{% block content %}

<h3><a href="{% url 'webapp:topic' topic.id %}">{{ topic }}</a></h3>

<form action="{% url 'webapp:edit_entry' entry.id %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
    <button name="submit" class="btn btn-primary">提交更改</button>
{% endbuttons %}
</form>
{% endblock content %}

webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}
{% block header %}
    <div class='jumbotron'>
        <h3>记录工作、生活、学习、读书……</h3>
        <h5>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">点击这里</a> 来创建账户

        </h5>
    </div>
{% endblock header %}
{% block content %}


{% endblock content %}

webapp/templates/webapp/new_entry.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>添加新的条目</h2>
{% endblock header %}

{% block content %}
 <h3><a href="{% url 'webapp:topic' topic.id %}">{{ topic }}</a></h3>

 <form action="{% url 'webapp:new_entry' topic.id %}" method='post' class="form">
{% csrf_token %}
 {% bootstrap_form form %}

{% buttons %}
<button name='submit' class="btn-primary">添加条目</button>
{% endbuttons %}
</form>
{% endblock content %}

webapp/templates/webapp/new_topic.html
{% extends "webapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>添加新的主题</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'webapp:new_topic' %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">提交</button>
    {% endbuttons %}
    </form>
{% endblock content %}

webapp/templates/webapp/topic.html
{% extends 'webapp/base.html' %}
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
        <h3><a href="{% url 'webapp:new_entry' topic.id %}">添加新的条目</a></h3>
    </p>
{% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'Y-m-d H:i:s' }}
                <small>
                    <a href="{% url 'webapp:edit_entry' entry.id %}">编辑</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
    </div> <!-- panel -->
{% empty %}
    没有新的条目
{% endfor %}
{% endblock content %}

webapp/templates/webapp/topics.html
{% extends "webapp/base.html" %}
{% block header %}
    <h1>主题</h1>
{% endblock header %}
{% block content %}
    <ul>
        {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'webapp:topic' topic.id %}">{{ topic }}</a>
            </h3>
        </li>
        {% empty %}
            <li>还没有添加主题</li>
        {% endfor %}
    </ul>
        <h3><a href="{% url 'webapp:new_topic' %}">添加新主题</h3>
{% endblock content %}